name: LiquidGlassDemo
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGNING_ALLOWED: "NO"
    CODE_SIGN_ENTITLEMENTS: ""
    DEVELOPMENT_TEAM: ""

packages:
  LiquidGlassEffect:
    path: ..

targets:
  LiquidGlassDemo:
    type: application
    platform: iOS
    sources:
      - path: LiquidGlassDemo
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: LiquidGlassEffect
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.LiquidGlassDemo
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        # 免签配置
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        AD_HOC_CODE_SIGNING_ALLOWED: "YES"
